---
swagger: "2.0"
info:
  description: "Identify crime prone areas near you"
  version: "1.0.0"
  title: "Crimes API"
  contact:
    name: "Crime prone location viewer"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /crimes:
    get:
      tags:
      - "Crimes"
      summary: "Crimes"
      description: "The Crimes endpoint returns information about the crimes previously\
        \ happened at a given location or nearby locations. The response includes\
        \ lists of crimes in the proper display order."
      operationId: "crimes_get"
      parameters:
      - name: "latitude"
        in: "query"
        description: "Latitude component of location."
        required: true
        type: "number"
        format: "double"
      - name: "longitude"
        in: "query"
        description: "Longitude component of location."
        required: true
        type: "number"
        format: "double"
      responses:
        200:
          description: "An array of Crimes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Crime"
        default:
          description: "Unexpected error while retrieving the crime list"
          schema:
            $ref: "#/definitions/Error"
      security:
      - apikey: []
      x-swagger-router-controller: "swagger_server.controllers.crimes_controller"
  /crimes/search:
    get:
      tags:
      - "Crimes"
      summary: "Search for a crime"
      description: "User can search for a perticluar crime with crime_id."
      operationId: "crimes_search_get"
      parameters:
      - name: "crime_id"
        in: "query"
        description: "Unique identifier representing a specific crime according to\
          \ chicago police."
        required: true
        type: "string"
      responses:
        200:
          description: "Crime Object"
          schema:
            type: "object"
            properties: {}
        default:
          description: "Unexpected error while retrieving the crime object for the\
            \ crime_id"
          schema:
            $ref: "#/definitions/Error"
      security:
      - apikey: []
      x-swagger-router-controller: "swagger_server.controllers.crimes_controller"
  /crimes/filter:
    get:
      tags:
      - "Crimes"
      summary: "crimeList based on primary_type"
      description: "The crimes/filter endpoint returns information about the crimes\
        \ previously happened at a given location or nearby locations based on user's\
        \ GPS coordinates and a primary_type (Example- BATTERY)."
      operationId: "crimes_filter_get"
      parameters:
      - name: "latitude"
        in: "query"
        description: "Latitude component of location."
        required: true
        type: "number"
        format: "double"
      - name: "longitude"
        in: "query"
        description: "Longitude component of location."
        required: true
        type: "number"
        format: "double"
      - name: "primary_type"
        in: "query"
        description: "primary_type of a crime."
        required: true
        type: "string"
      responses:
        200:
          description: "An array of Crimes"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Crime"
        default:
          description: "Unexpected error while retrieving the crime list"
          schema:
            $ref: "#/definitions/Error"
      security:
      - apikey: []
      x-swagger-router-controller: "swagger_server.controllers.crimes_controller"
securityDefinitions:
  apikey:
    type: "apiKey"
    name: "server_token"
    in: "query"
definitions:
  Crime:
    type: "object"
    required:
    - "crime_id"
    properties:
      crime_id:
        type: "string"
        description: "Unique identifier representing a specific crime according to\
          \ chicago police."
      case_number:
        type: "string"
        description: "Case Number."
      date:
        type: "string"
        description: "Date of the crime."
      block:
        type: "string"
        description: "Block Address."
      crime_code:
        type: "string"
        description: "IUCR by chicago police."
      primary_description:
        type: "string"
        description: "Primary Type."
      secondary_description:
        type: "string"
        description: "Description."
      location_cat:
        type: "string"
        description: "Location Description/catogery."
      arrested:
        type: "boolean"
        description: "Arrested."
      domestic:
        type: "boolean"
        description: "Domestic."
      beat_code:
        type: "string"
        description: "Beat Code."
      district_code:
        type: "string"
        description: "District Code."
      ward_code:
        type: "string"
        description: "Ward Code."
      community_area_code:
        type: "string"
        description: "Community Area code."
      fbi_code:
        type: "string"
        description: "FBI Code."
      x_coordinate:
        type: "string"
        description: "X Coordinate."
      y_coordinate:
        type: "string"
        description: "Y Coordinate."
      year:
        type: "string"
        description: "Year of the crime."
      updated_on:
        type: "string"
        description: "Last Updated On."
      latitude:
        type: "string"
        description: "Latitude."
      longitude:
        type: "string"
        description: "Longitude."
      gps_location:
        type: "string"
        description: "GPS Location."
    example:
      date: "date"
      primary_description: "primary_description"
      x_coordinate: "x_coordinate"
      updated_on: "updated_on"
      arrested: true
      year: "year"
      ward_code: "ward_code"
      location_cat: "location_cat"
      latitude: "latitude"
      y_coordinate: "y_coordinate"
      fbi_code: "fbi_code"
      domestic: true
      gps_location: "gps_location"
      secondary_description: "secondary_description"
      district_code: "district_code"
      beat_code: "beat_code"
      case_number: "case_number"
      block: "block"
      crime_id: "crime_id"
      community_area_code: "community_area_code"
      crime_code: "crime_code"
      longitude: "longitude"
  Error:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
